name: saarthi
description: Find Your Accessible Way
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.6.0
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  google_maps_flutter: ^2.5.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/saarthi_logo.png 